language: cpp

compiler:
  - gcc

before_install:
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-add-repository -y ppa:onedata/build-deps && sudo apt-get update && sudo apt-get install -y google-glog gtest; fi

before_script:
  - rm -rf build
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=dist -DINCLUDE_SYSTEM_DIRS=1 ../

script: make gtest VERBOSE=ON

branches:
  only:
    - master

os:
  - linux
