language: cpp

compiler:
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-add-repository -y ppa:onedata/build-deps && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install -y cmake gcc-5 g++-5 libgoogle-glog-dev libgtest-dev && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5; fi

install:
  - if [ $TRAVIS_OS_NAME == linux ]; then pushd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib && popd; fi

before_script:
  - rm -rf build
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=dist -DINCLUDE_SYSTEM_DIRS=1 ..

script: make gtest VERBOSE=ON

branches:
  only:
    - master

os:
  - linux
